source 'http://ruby.taobao.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'bcrypt'

gem 'sass'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'

gem 'erubis', '~> 2.7.0'
gem 'activerecord', '>= 4.0', :require => 'active_record'
gem 'sqlite3'

# Test requirements
gem 'rspec', :group => 'test'
gem 'rack-test', :require => 'rack/test', :group => 'test'

# Padrino Stable Gem
gem 'padrino', '0.12.5'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.12.5'
# end

gem 'redis', '3.2.0'
gem 'connection_pool'

gem 'second_level_cache', '~> 2.1'

# gem 'unicorn', :group => :production
gem 'rainbows', :group => :production
